# Generated by Django 4.0.1 on 2022-02-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bulletin', '0002_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
