# Generated by Django 4.0.1 on 2022-02-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bulletin', '0003_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
